import { GoogleGenerativeAI } from "@google/generative-ai";

/**
 * Builds a prompt for the Gemini API based on the user's question and plant information.
 * Generated by Codex, reviewed and edited by Tyson Nguyen.
 *
 * @author https://openai.com/codex/
 *
 * @param {*} question
 * @param {*} plantInfo
 *
 * @returns {string} The constructed prompt to be sent to the Gemini API.
 */
function buildPrompt(question, plantInfo) {
	const infoLines = [
		`Name: ${plantInfo.name}`,
		plantInfo.description ? `Description: ${plantInfo.description}` : null,
		plantInfo.season ? `Season: ${plantInfo.season}` : null,
		plantInfo.location ? `Location: ${plantInfo.location}` : null,
	].filter(Boolean);

	return [
		"You are a foraging safety assistant.",
		"Prioritize safety over identification or edibility claims.",
		"Rules:",
		"- Never guarantee a plant or mushroom is safe to eat.",
		"- Warn about dangerous lookalikes and common misidentification risks.",
		"- Encourage expert verification and multiple sources before consumption.",
		"- Give concise, beginner-friendly answers.",
		"- Avoid hallucinated or overly specific claims.",
		"- Focus on safety-first guidance.",
		"",
		"Plant info:",
		...infoLines,
		"",
		`User question: ${question}`,
		"",
		"Answer in 3-6 short sentences.",
	].join("\n");
}

/**
 * Asks the Gemini API a question about a plant.
 * Generated by Codex, reviewed and edited by Tyson Nguyen.
 *
 * @author https://openai.com/codex/
 *
 * @param {*} question
 * @param {*} plantInfo
 * @returns {Promise<string>} The answer from the Gemini API.
 *
 * @throws Will throw an error if the GEMINI_API_KEY is not set or if the API request fails.
 */
export async function askGemini(question, plantInfo) {
	const apiKey = process.env.GEMINI_API_KEY;
	if (!apiKey) {
		const error = new Error("GEMINI_API_KEY is not set");
		error.code = "MISSING_API_KEY";
		throw error;
	}

	const genAI = new GoogleGenerativeAI(apiKey);
	const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });
	const prompt = buildPrompt(question, plantInfo);
	const result = await model.generateContent(prompt);
	const text = result?.response?.text?.();

	if (!text) {
		throw new Error("Empty response from Gemini");
	}

	return text.trim();
}
