import { useEffect, useRef, useState } from "react";

/**
 *  HeartExplosion component renders a burst of heart particles at a given (x, y) coordinate.
 *  Each heart particle has a random initial velocity and is affected by gravity, creating a natural explosion effect.
 *
 * Generated by ChatGPT Copilot reviewed by Tyson Nguyen
 *
 * @author https://copilot.com
 */

type HeartParticle = {
	id: number;
	x: number;
	y: number;
	vx: number;
	vy: number;
	life: number; // 0 → 1
};

type HeartExplosionProps = {
	x: number; // starting x in px (relative to container)
	y: number; // starting y in px
	count?: number;
	duration?: number; // ms
};

export function HeartExplosion({ x, y, count = 5, duration = 1200 }: HeartExplosionProps) {
	const [particles, setParticles] = useState<HeartParticle[]>(() => {
		const newParticles: HeartParticle[] = [];
		for (let i = 0; i < count; i++) {
			const angle = Math.random() * Math.PI * 2;
			const speed = 1.5 + Math.random() * 3; // tweak for more/less boom
			newParticles.push({
				id: i,
				x,
				y,
				vx: Math.cos(angle) * speed,
				vy: Math.sin(angle) * speed - 2, // initial upward bias
				life: 0,
			});
		}
		return newParticles;
	});
	const startTimeRef = useRef<number | null>(null);
	const rafRef = useRef<number | null>(null);

	useEffect(() => {
		const gravity = 0.05;

		const step = (timestamp: number) => {
			if (startTimeRef.current == null) startTimeRef.current = timestamp;
			const elapsed = timestamp - startTimeRef.current;
			const t = Math.min(1, elapsed / duration); // 0 → 1

			setParticles(prev =>
				prev.map(p => {
					const nx = p.x + p.vx;
					const ny = p.y + p.vy;
					const nvy = p.vy + gravity;
					return {
						...p,
						x: nx,
						y: ny,
						vy: nvy,
						life: t,
					};
				})
			);

			if (elapsed < duration) {
				rafRef.current = requestAnimationFrame(step);
			}
		};

		rafRef.current = requestAnimationFrame(step);

		return () => {
			if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
		};
	}, [duration]);

	if (particles.length === 0) return null;

	return (
		<div
			style={{
				position: "absolute",
				inset: 0,
				pointerEvents: "none",
				overflow: "visible",
			}}
		>
			{particles.map(p => {
				const opacity = 1 - p.life; // fade out
				const scale = 0.8 + 0.4 * (1 - p.life);
				return (
					<div
						key={p.id}
						style={{
							position: "absolute",
							left: p.x,
							top: p.y,
							transform: `translate(-50%, -50%) scale(${scale})`,
							opacity,
							transition: "opacity 0.1s linear",
							color: "#ff4b8b",
							fontSize: "20px",
							filter: "drop-shadow(0 0 4px rgba(255,75,139,0.6))",
						}}
					>
						❤️
					</div>
				);
			})}
		</div>
	);
}
